### ISSUE TITLE
gnome-mpv

### ISSUE THREAD

**Issue by bmeznarsic** [solus-project/repository#36]
http://hastebin.com/afafekefip.pas

![screenshot from 2015-05-15 22-21-13](https://cloud.githubusercontent.com/assets/6306479/7661198/dcefdb3e-fb50-11e4-88c3-e79ff533477b.png)
![screenshot from 2015-05-15 22-21-03](https://cloud.githubusercontent.com/assets/6306479/7661199/dcf0df8e-fb50-11e4-92c8-f1c076218e82.png)
![screenshot from 2015-05-15 22-20-54](https://cloud.githubusercontent.com/assets/6306479/7661203/dcf31d94-fb50-11e4-84fc-be1c7b43f38d.png)
![screenshot from 2015-05-15 22-20-47](https://cloud.githubusercontent.com/assets/6306479/7661201/dcf27dd0-fb50-11e4-99c2-41cd34f7d1c0.png)
![screenshot from 2015-05-15 22-20-38](https://cloud.githubusercontent.com/assets/6306479/7661200/dcf266e2-fb50-11e4-823c-195a994b580b.png)
![screenshot from 2015-05-15 22-20-27](https://cloud.githubusercontent.com/assets/6306479/7661202/dcf2ea22-fb50-11e4-9298-8bab93463b68.png)
![screenshot from 2015-05-15 22-18-25](https://cloud.githubusercontent.com/assets/6306479/7661204/dd04f8d4-fb50-11e4-9841-7b045f5e31a9.png)

**Comment by ikeydoherty** [comment]
Odd I cannot recreate the issue you have. I have spammy output, but not that. Any way that you can get the file to me so I can see if i can recreate said issue?

My output, fwiw:
```
$ gnome-mpv demo.mkv 
/usr/bin/xdg-screensaver: line 413: xset: command not found

=================================================================
==10575==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3328 byte(s) in 5 object(s) allocated from:
    #0 0x4a8fee in realloc (/usr/bin/gnome-mpv+0x4a8fee)
    #1 0x7ff802275469 (/usr/lib/libfontconfig.so.1+0x1a469)

Direct leak of 680 byte(s) in 17 object(s) allocated from:
    #0 0x4a8e50 in __interceptor_calloc (/usr/bin/gnome-mpv+0x4a8e50)
    #1 0x7ff80645aa51 in g_malloc0 (/usr/lib/libglib-2.0.so.0+0x4ea51)

Direct leak of 272 byte(s) in 17 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7ff80645a9f9 in g_malloc (/usr/lib/libglib-2.0.so.0+0x4e9f9)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7ff802275519 (/usr/lib/libfontconfig.so.1+0x1a519)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x4a8fee in realloc (/usr/bin/gnome-mpv+0x4a8fee)
    #1 0x7ff80645aabd in g_realloc (/usr/lib/libglib-2.0.so.0+0x4eabd)

Indirect leak of 6080 byte(s) in 190 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7ff802265d2f (/usr/lib/libfontconfig.so.1+0xad2f)

Indirect leak of 4224 byte(s) in 132 object(s) allocated from:
    #0 0x4a8e50 in __interceptor_calloc (/usr/bin/gnome-mpv+0x4a8e50)
    #1 0x7ff802275bc9 (/usr/lib/libfontconfig.so.1+0x1abc9)

Indirect leak of 3133 byte(s) in 273 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7ff8053f4029 in __strdup (/lib/libc.so.6+0x8b029)

Indirect leak of 1280 byte(s) in 40 object(s) allocated from:
    #0 0x4a8e50 in __interceptor_calloc (/usr/bin/gnome-mpv+0x4a8e50)
    #1 0x7ff80227507c (/usr/lib/libfontconfig.so.1+0x1a07c)

Indirect leak of 1003 byte(s) in 17 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7ff8019eb635 in pcre_compile2 (/usr/lib/libpcre.so.1+0xb635)

Indirect leak of 384 byte(s) in 12 object(s) allocated from:
    #0 0x4a8e50 in __interceptor_calloc (/usr/bin/gnome-mpv+0x4a8e50)
    #1 0x7ff8022750d5 (/usr/lib/libfontconfig.so.1+0x1a0d5)

Indirect leak of 192 byte(s) in 6 object(s) allocated from:
    #0 0x4a8e50 in __interceptor_calloc (/usr/bin/gnome-mpv+0x4a8e50)
    #1 0x7ff802274f74 (/usr/lib/libfontconfig.so.1+0x19f74)

Indirect leak of 144 byte(s) in 3 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7ff80227015d in FcLangSetCreate (/usr/lib/libfontconfig.so.1+0x1515d)

Indirect leak of 134 byte(s) in 34 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7ff80645a9f9 in g_malloc (/usr/lib/libglib-2.0.so.0+0x4e9f9)

SUMMARY: AddressSanitizer: 21126 byte(s) leaked in 748 allocation(s).
```

**Comment by bmeznarsic** [comment]
https://drive.google.com/file/d/0BxfRw5EwE_LLMHdsZXUzcTJFQ3c/view?usp=sharing

**Comment by ikeydoherty** [comment]
I can recreate it with that particular file. What app was used to create the screencast? Could be its creating a dodgy file.

**Comment by bmeznarsic** [comment]
vlc

**Comment by ikeydoherty** [comment]
Do you get the same problems when using simplescreenrecorder? It could be VLC is producing corrupt streams

**Comment by bmeznarsic** [comment]
I'll test that soon-ish. Watching the Vocal livestream. :P

**Comment by ikeydoherty** [comment]
lol fair do :p

**Comment by bmeznarsic** [comment]
https://drive.google.com/file/d/0BxfRw5EwE_LLQXVtUzBrLW1OblE/view?usp=sharing

I get the same kind of error windows.

Outputˇ

$ gnome-mpv '/home/blaz/ssc-test1.mp4' 
/usr/bin/xdg-screensaver: 338: [: xbudgie-desktop: unexpected operator
/usr/bin/xdg-screensaver: 413: /usr/bin/xdg-screensaver: xset: not found
/usr/bin/xdg-screensaver: 712: /usr/bin/xdg-screensaver: xset: not found

=================================================================
==1942==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4608 byte(s) in 7 object(s) allocated from:
    #0 0x4a8fee in realloc (/usr/bin/gnome-mpv+0x4a8fee)
    #1 0x7f66d9754469 (/usr/lib/libfontconfig.so.1+0x1a469)

Direct leak of 680 byte(s) in 17 object(s) allocated from:
    #0 0x4a8e50 in __interceptor_calloc (/usr/bin/gnome-mpv+0x4a8e50)
    #1 0x7f66dd939a51 in g_malloc0 (/usr/lib/libglib-2.0.so.0+0x4ea51)

Direct leak of 272 byte(s) in 17 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7f66dd9399f9 in g_malloc (/usr/lib/libglib-2.0.so.0+0x4e9f9)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7f66d9754519 (/usr/lib/libfontconfig.so.1+0x1a519)

Direct leak of 40 byte(s) in 2 object(s) allocated from:
    #0 0x4a8fee in realloc (/usr/bin/gnome-mpv+0x4a8fee)
    #1 0x7f66bd91fb28 (/usr/lib/dri/nouveau_dri.so+0x3bab28)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x4a8fee in realloc (/usr/bin/gnome-mpv+0x4a8fee)
    #1 0x7f66dd939abd in g_realloc (/usr/lib/libglib-2.0.so.0+0x4eabd)

Indirect leak of 9056 byte(s) in 283 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7f66d9744d2f (/usr/lib/libfontconfig.so.1+0xad2f)

Indirect leak of 5920 byte(s) in 185 object(s) allocated from:
    #0 0x4a8e50 in __interceptor_calloc (/usr/bin/gnome-mpv+0x4a8e50)
    #1 0x7f66d9754bc9 (/usr/lib/libfontconfig.so.1+0x1abc9)

Indirect leak of 4041 byte(s) in 345 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7f66dc8d3029 in __strdup (/lib/libc.so.6+0x8b029)

Indirect leak of 1017 byte(s) in 12 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7f66dd65da83 (/usr/lib/libmpv.so.1+0x109a83)

Indirect leak of 1003 byte(s) in 17 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7f66d8eca635 in pcre_compile2 (/usr/lib/libpcre.so.1+0xb635)

Indirect leak of 512 byte(s) in 16 object(s) allocated from:
    #0 0x4a8e50 in __interceptor_calloc (/usr/bin/gnome-mpv+0x4a8e50)
    #1 0x7f66d97540d5 (/usr/lib/libfontconfig.so.1+0x1a0d5)

Indirect leak of 320 byte(s) in 4 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7f66dd65d9f0 (/usr/lib/libmpv.so.1+0x1099f0)

Indirect leak of 256 byte(s) in 8 object(s) allocated from:
    #0 0x4a8e50 in __interceptor_calloc (/usr/bin/gnome-mpv+0x4a8e50)
    #1 0x7f66d9753f74 (/usr/lib/libfontconfig.so.1+0x19f74)

Indirect leak of 192 byte(s) in 4 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7f66d974f15d in FcLangSetCreate (/usr/lib/libfontconfig.so.1+0x1515d)

Indirect leak of 134 byte(s) in 34 object(s) allocated from:
    #0 0x4a8cfb in __interceptor_malloc (/usr/bin/gnome-mpv+0x4a8cfb)
    #1 0x7f66dd9399f9 in g_malloc (/usr/lib/libglib-2.0.so.0+0x4e9f9)

SUMMARY: AddressSanitizer: 28323 byte(s) leaked in 953 allocation(s).

**Comment by bmeznarsic** [comment]
I really should test these on another system. I'll get back to you on that.

**Comment by Justinzobel** [comment]
xset has been added to the repos, you still having isssues @bmeznarsic ?

**Comment by bmeznarsic** [comment]
I installed xset. I recorded my desktop with VLC again. Still the same errors. I think this is an upstream issue.

**Comment by Justinzobel** [comment]
Yeah it plays for me but with errors. Can you test just with mpv from the
command line? If the errors are the same then we can report it upstream to
mpv instead of gnome mpv.

**Comment by bmeznarsic** [comment]
http://hastebin.com/owukafobuh.mel

**Comment by Justinzobel** [comment]
Looks to be the same. Not at pc to confirm. If it is please submit to mpv
and see what they say.
